apiVersion: v1
kind: Secret
metadata:
  name: swap-reporting-secrets
  namespace: swap-reporting
type: Opaque # Use Opaque type for arbitrary data
data:
  # Database Credentials (Base64 encoded)
  # Example: echo -n 'your_db_user' | base64
  DATABASE_USER: <base64_encoded_db_user>
  DATABASE_PASSWORD: <base64_encoded_db_password>
  DATABASE_NAME: <base64_encoded_db_name>
  # DATABASE_HOST and DATABASE_PORT can be in ConfigMap if database is internal to cluster,
  # or external if connecting to a managed service.

  # AWS S3 Credentials (Base64 encoded)
  # Example: echo -n 'YOUR_AWS_ACCESS_KEY_ID' | base64
  AWS_ACCESS_KEY_ID: <base64_encoded_aws_access_key_id>
  AWS_SECRET_ACCESS_KEY: <base64_encoded_aws_secret_access_key>

  # SDR Credentials (Base64 encoded)
  # Example: echo -n 'your_sdr_api_key' | base64
  # SDR_API_KEY: <base64_encoded_sdr_api_key>
  # SDR_SFTP_PASSWORD: <base64_encoded_sdr_sftp_password>
  # SDR_SFTP_PRIVATE_KEY: <base64_encoded_sdr_sftp_private_key_content> # Store key content here

# Note: Create this file carefully with actual base64 encoded values.
# Do not commit actual secrets to your source code repository.
