apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-deployment
  namespace: swap-reporting
spec:
  replicas: 2 # Run 2 instances
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
      - name: validation
        image: your-docker-registry/validation:latest # Replace with your image
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: swap-reporting-config
              key: DATABASE_URL
        # Configure downstream service URLs
        - name: REPORT_GENERATION_MODULE_URL
          value: http://report-generation-service:8003/generate-report
        - name: ERROR_MONITOR_MODULE_URL
          value: http://error-monitoring-service:8005/report_error
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 10
